---
- name: installing java on all nodes
  become: yes
  hosts: all
  tasks:
    - name: install apche2
      ansible.builtin.apt:
        name: apache2
        update_cache: yes
        state: present