---
- name: installing java on all nodes
  become: yes
  hosts: all
  tasks:
    - name: install java
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present